; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:d1_mini]
platform = espressif8266
board = d1_mini
framework = arduino
monitor_speed = 115200
build_flags = -DELEGANTOTA_USE_ASYNC_WEBSERVER=1 -Wall -Wextra -Wformat=2
lib_deps = 
   Servo
   https://github.com/me-no-dev/ESPAsyncWebServer.git
   https://github.com/me-no-dev/ESPAsyncTCP.git
   ayushsharma82/ElegantOTA @ ^3.0.0
   ArduinoJson
   knolleary/PubSubClient@^2.8.0
   
; Bibliotheksabhängigkeiten können auf verschiedene Arten angegeben werden:
;    Einfach (ok): lib_deps = PubSubClient
;    Spezifisch (besser): lib_deps = knolleary/PubSubClient
;    Empfohlen (fixe Quelle + Version): lib_deps = knolleary/PubSubClient@^2.8.0
;    Strikt (genaue Version): lib_deps = knolleary/PubSubClient@2.8.0
;    Fork/Branch: lib_deps = https://github.com/user/PubSubClient.git#mein-branch
